global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bizscore-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bizscore-app:8080']
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']